TangraTravel/TangraTravel.MVC/Models/FeedbackDtos/FeedbackViewModel.cs
using System.ComponentModel.DataAnnotations;

using Microsoft.AspNetCore.Mvc.Rendering;

namespace TangraTravel.MVC.Models.FeedbackDto
{
    public class FeedbackViewModel
    {
        public int TravelId { get; set; }

        public int TargetId { get; set; }
        public SelectList Targets { get; set; }

        [Range(0, 5, ErrorMessage = "{0} value can be between {2} to {1}")]
        public int Rating { get; set; }

        [MaxLength(255, ErrorMessage = "{0} value must be between and {1} symbols!")]
        public string Comment { get; set; }
    }
}

TangraTravel/TangraTravel.MVC/Controllers/FeedbackController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

using TangraTravel.MVC.Mapper;
using TangraTravel.Service.Contracts;
using TangraTravel.MVC.Models.FeedbackDto;
using TangraTravel.MVC.Controllers.Abstract;
using TangraTravel.Service.Models.TravelDtos;
using TangraTravel.Service.Models.FeedbackDtos;

namespace TangraTravel.MVC.Controllers
{
    public class FeedbackController : BaseController
    {
        private readonly IFeedbackService feedbackService;
        private readonly ICustomerService customerService;
        private readonly ITravelService travelService;

        public FeedbackController(IFeedbackService feedbackService, ICustomerService customerService, ITravelService travelService)
        {
            this.feedbackService = feedbackService;
            this.customerService = customerService;
            this.travelService = travelService;
        }

        [Authorize]
        public async Task<IActionResult> Index(int page, int byPage)
        {
            var customers = await this.customerService.GetCustomersByPageAsync(page, byPage);
            var view = new FeedbackIndexByPageViewModel(byPage)
            {
                Page = page,
                MaxPage = await this.customerService.MaxPage(byPage),
                FeedbackCustomers = customers.Select(x => x.ToFeedbackCustomerViewModel()).ToArray()
            };
            return View(view);
        }

        [Authorize]
        public async Task<IActionResult> Selected(int userId, int page)
        {
            int byPage = 3;
            int maxPage = await this.feedbackService.MaxPageAsync(userId, byPage, IsGiven: false);
            var feedbacks = await this.feedbackService.ReceivedFeedback(userId, page, byPage);

            var view = new FeedbackSelectedByPageViewModel()
            {
                SelectedUserId = userId,
                Page = page,
                MaxPage = maxPage,
                FeedbackComments = feedbacks.Select(x => x.ToFeedbackCommentViewModel()).ToArray()
            };

            return this.View(view);
        }

        [Authorize(Roles = "Driver, Passenger")]
        public async Task<IActionResult> FromMe(int page)
        {
            int byPage = 3;
            int customerId = this.GetUserId();
            int maxPage = await this.feedbackService.MaxPageAsync(customerId, byPage, IsGiven: true);
            var feedbacks = await this.feedbackService.GivenFeedback(customerId, page, byPage);

            var view = new FeedbackByPageViewModel()
            {
                Page = page,
                MaxPage = maxPage,
                FeedbackComments = feedbacks.Select(x => x.ToFeedbackCommentViewModel()).ToArray()
            };

            return this.View(view);
        }

        [Authorize(Roles = "Driver, Passenger")]
        public async Task<IActionResult> ThowardsMe(int page)
        {
            int byPage = 3;
            int customerId = this.GetUserId();
            int maxPage = await this.feedbackService.MaxPageAsync(customerId, byPage, IsGiven: false);
            var feedbacks = await this.feedbackService.ReceivedFeedback(customerId, page, byPage);

            var view = new FeedbackByPageViewModel()
            {
                Page = page,
                MaxPage = maxPage,
                FeedbackComments = feedbacks.Select(x => x.ToFeedbackCommentViewModel()).ToArray()
            };

            return this.View(view);
        }

        [Authorize(Roles = "Driver, Passenger")]
        public async Task<IActionResult> ApplyComment(int page)
        {
            int userId = this.GetUserId();
            var travelInformation = await this.travelService.RetriveCompletedTravelsAsync(userId, page);
            var view = new FeedbackApplyViewModel
            {
                Page = page,
                Travels = travelInformation
            };

            return this.View(view);
        }

        [HttpGet]
        [Authorize(Roles = "Driver")]
        public async Task<IActionResult> DriverFeedback(int travelId)
        {
            var passengers = await this.travelService.RetrivePassengerInFinishedTravelsAsync(travelId);
            if (passengers.Count == 0)
            {
                this.RedirectToAction("ApplyComment", 1);
            }

            var selectList = new SelectList(passengers, "TargetId", "TargetInformation");
            var view = new FeedbackViewModel
            {
                TravelId = travelId,
                Targets = selectList
            };

            return this.View(view);
        }

        [HttpPost]
        [Authorize(Roles = "Driver")]
        public async Task<IActionResult> DriverFeedback(int travelId, FeedbackViewModel inputs)
        {
            IList<TravelCustomer> passengers = null;
            SelectList selectList = null;
            if (!ModelState.IsValid)
            {
                passengers = await this.travelService.RetrivePassengerInFinishedTravelsAsync(travelId);
                selectList = new SelectList(passengers, "PassengerId", "PassengerInformation");
                inputs.TravelId = travelId;
                inputs.Targets = selectList;
                return this.View(inputs);
            }

            int driverId = this.GetUserId();
            var feedback = new FeedbackCreateDto
            {
                Rating = inputs.Rating,
                Comment = inputs.Comment,
                TravelId = travelId,
                TargetId = inputs.TargetId
            };
            try
            {
                var result = await this.feedbackService.DriverWriteFeedbackAsync(driverId, feedback);

                passengers = await this.travelService.RetrivePassengerInFinishedTravelsAsync(travelId);
                if (passengers.Count == 0)
                {
                    return this.RedirectToAction("ApplyComment", 1);
                }
                selectList = new SelectList(passengers, "PassengerId", "PassengerInformation");
                var view = new FeedbackViewModel
                {
                    TravelId = travelId,
                    Targets = selectList
                };
                return this.View(view);
            }
            catch (ApplicationException ae)
            {
                return this.RedirectToAction("Index", "Customer");
            }
        }

        [HttpGet]
        [Authorize(Roles = "Passenger")]
        public async Task<IActionResult> PassengerFeedback(int travelId)
        {
            int userId = this.GetUserId();
            var driver = await this.travelService.RetriveDriverInFinishedTravelAsync(travelId, userId);
            if (driver == null)
            {
                return this.RedirectToAction("ApplyComment", 1);
            }

            var selectList = new SelectList(new List<TravelCustomer> { driver }, "TargetId", "TargetInformation");
            var view = new FeedbackViewModel
            {
                TravelId = travelId,
                Targets = selectList
            };

            return this.View(view);
        }

        [HttpPost]
        [Authorize(Roles = "Passenger")]
        public async Task<IActionResult> PassengerFeedback(int travelId, FeedbackViewModel inputs)
        {
            int passengerId = this.GetUserId();
            TravelCustomer driver = null;
            SelectList selectList = null;
            if (!ModelState.IsValid)
            {
                driver = await this.travelService.RetriveDriverInFinishedTravelAsync(travelId, passengerId);
                selectList = new SelectList(new List<TravelCustomer> { driver }, "TargetId", "TargetInformation");
                inputs.TravelId = travelId;
                inputs.Targets = selectList;
                return this.View(inputs);
            }
           
            var feedback = new FeedbackCreateDto
            {
                Rating = inputs.Rating,
                Comment = inputs.Comment,
                TravelId = travelId,
                TargetId = inputs.TargetId
            };
            try
            {
                var result = await this.feedbackService.PassengerWriteFeedbackAsync(passengerId, feedback);

                return this.RedirectToAction("ApplyComment", 1);
            }
            catch (ApplicationException)
            {
                return this.RedirectToAction("Index", "Customer");
            }
        }

        [Authorize(Roles = "Driver, Passenger")]
        public async Task<IActionResult> GetFeedback(int feedbackId)
        {
            var view = await this.feedbackService.GetFeedbackAsync(feedbackId);

            return this.View(view);
        }
    }
}

TangraTravel/TangraTravel.MVC/Views/Feedback/ApplyComment.cshtml
@model TangraTravel.MVC.Models.FeedbackDto.FeedbackApplyViewModel
@{
    ViewData["Title"] = "Apply Feedbacks";
    int index = 1;
}

<div class="container-fluid px-6 py-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <!-- Page header -->
            <div>
                <div class="border-bottom pb-4 mb-4 ">
                    <div class="mb-2 mb-lg-0">
                        <h3 class="mb-0 fw-bold">Select Travel for giving Feedbacks</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (Model.Travels.Count == 0)
    {
        <h3 class="mb-0 fw-bold">All feedbacks are given</h3>
    }
    else
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Start Point</th>
                    <th scope="col">End Point</th>
                    <th scope="col">Arrival Date</th>
                    <th scope="col">Role</th>
                    <th scope="col">Apply</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Travels)
                {
                    <tr>
                        <th scope="row">@(index++)</th>
                        <td>@item.StartPoint</td>
                        <td>@item.EndPoint</td>
                        <td>@item.ArrivalDate</td>
                        <td>@item.Role</td>
                        <td>
                            @if (item.Role == "Passenger")
                            {
                                <a class="btn btn-outline-dark"
                                   asp-controller="Feedback" asp-action="PassengerFeedback" asp-route-travelId="@item.TravelId">
                                    Feedbacks
                                </a>
                            }
                            else
                            {
                                <a class="btn btn-outline-dark"
                                   asp-controller="Feedback" asp-action="DriverFeedback" asp-route-travelId="@item.TravelId">
                                    Feedbacks
                                </a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @if (Model.Page > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="ApplyComment"
                           asp-route-page="@(Model.Page - 1)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                }
                @if (Model.Travels.Count != 0)
                {
                    <li class="page-item"><a class="page-link" href="#">@Model.Page</a></li>
                }
                else
                {
                    <li class="page-item"><a class="page-link"  asp-action="ApplyComment"
                           asp-route-page="1)">In the begining</a></li>
                }
                @if (Model.Travels.Count != 0)
                {
                    <li class="page-item">
                        <a class="page-link"
                           asp-action="ApplyComment"
                           asp-route-page="@(Model.Page + 1)" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    }
</div>

TangraTravel/TangraTravel.MVC/Views/Feedback/DriverFeedback.cshtml
@model TangraTravel.MVC.Models.FeedbackDto.FeedbackViewModel
@{
    ViewData["Title"] = "ApplyComments";
}


<div class="container-fluid px-6 py-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <!-- Page header -->
            <div>
                <div class="border-bottom pb-4 mb-4 ">
                    <div class="mb-2 mb-lg-0">
                        <h3 class="mb-0 fw-bold">Create Feedback</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <!-- card header  -->
        <div class="card-header p-4 bg-white">
            <h4 class="mb-0">Feedback details</h4>
        </div>
        <!-- card body  -->
        <div class="card-body">
            <!-- row  -->
            <form asp-action="DriverFeedback" asp-route-travelId="@Model.TravelId" method="post">
                <!-- row -->
                <div class="mb-3 row">
                    <label asp-for="TargetId" class="col-sm-3 col-form-label form-label">Location</label>
                    <div class="col-md-9 col-12">
                        <select asp-for="TargetId" asp-items="Model.Targets" class="form-select" id="status">
                        </select>
                    </div>
                </div>
                <!-- row -->
                <div class="mb-3 row">
                    <label asp-for="Rating" class="col-sm-3 col-form-label form-label">End point</label>
                    <div class="col-md-9 col-12">
                        <select asp-for="Rating" value="@this.Model.Rating" class="form-select" id="status">
                            @for (int i = 0; i <= 5; i++)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                    </div>
                </div>
                <!-- Textarea -->
                <div class="mb-3 row">
                    <label for="Comment" class="col-sm-3 col-form-label form-label">Optional comment</label>
                    <div class="col-sm-9 mb-3 mb-lg-0">
                        <textarea asp-for="Comment" value="@this.Model.Comment" class="form-control" id="comment" rows="5"></textarea>
                    </div>
                </div>
                <!-- button -->
                <div class="offset-md-3 col-md-8 col-12 mt-3">
                    <button type="submit" class="btn btn-primary"> Submit </button>
                </div>
            </form>
        </div>
    </div>
</div>

TangraTravel/TangraTravel.MVC/Views/Feedback/FromMe.cshtml
@model TangraTravel.MVC.Models.FeedbackDto.FeedbackByPageViewModel
@{
    ViewData["Title"] = "Posted Feedbacks";
    ViewData["Action"] = "FromMe";
}

<partial name="_PersonalFeedbacks" />

TangraTravel/TangraTravel.MVC/Views/Feedback/GetFeedback.cshtml
@model TangraTravel.Service.Models.FeedbackDtos.FeedbackReturnDto
@{
    ViewData["Title"] = "Feedback";
}
<div class="container-fluid px-6 py-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <!-- Page header -->
            <div>
                <div class="border-bottom pb-4 mb-4 ">
                    <div class="mb-2 mb-lg-0">
                        <h3 class="mb-0 fw-bold">Feedback</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="py-1">
        <div class="col-xl-12 col-lg-12 col-md-12 col-12 mb-12">
            <div class="row">
                <div class="card margin-bot-2rem inline-flex-card">
                    <div class="card-body">
                        <h4 class="card-title">Rating: @Model.Rating</h4>
                        <h5 class="card-title">Author: @Model.Author, Username: @Model.AuthorUsername</h5>
                        <h5 class="card-title">Recepient: @Model.Target, Username: @Model.TargetUsername</h5>
                        @*<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>*@
                        <p class="card-text">Commetnt: @Model.Comment</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TangraTravel/TangraTravel.MVC/Views/Feedback/Index.cshtml
@model TangraTravel.MVC.Models.FeedbackDto.FeedbackIndexByPageViewModel
@{
    ViewData["Title"] = "Feedbacks Table";
    int i = 1;
}

<div class="container-fluid px-6 py-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <!-- Page header -->
            <div>
                <div class="border-bottom pb-4 mb-4 ">
                    <div class="mb-2 mb-lg-0">
                        <h3 class="mb-0 fw-bold">Customer Feedbacks</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Avatar</th>
                <th scope="col">Full Name</th>
                <th scope="col">Rating</th>
                <th scope="col">Username</th>
                <th scope="col">Status</th>
                <th scope="col">To Feedbacks</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.FeedbackCustomers)
            {
                <tr>
                    <th scope="row">@(i++)</th>
                    <td>
                        <div class="avatar">
                            <img alt="N/A" src=@item.AvatarUrl class="rounded-circle" />
                        </div>
                    </td>
                    <td>@item.FullName</td>
                    <td>@item.Rating</td>
                    <td>@item.UserName</td>
                    <td>@item.Role</td>
                    <td>
                        <a class="btn btn-outline-dark"
                           asp-controller="Feedback" asp-action="Selected" asp-route-userId="@item.CustomerId" asp-route-page="1">
                            Feedbacks
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @if (Model.Page > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="Index"
                       asp-route-page="@(Model.Page-1)"
                       asp-route-byPage="@Model.ByPage" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }
            <li class="page-item"><a class="page-link" href="#">@Model.Page</a></li>
            @if (Model.Page + 1 <= Model.MaxPage)
            {
                <li class="page-item">
                    <a class="page-link"
                       asp-action="Index"
                       asp-route-page="@(Model.Page+1)"
                       asp-route-byPage="@Model.ByPage" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
        </ul>
    </nav>
</div>

TangraTravel/TangraTravel.MVC/Views/Feedback/PassengerFeedback.cshtml
@model TangraTravel.MVC.Models.FeedbackDto.FeedbackViewModel
@{
    ViewData["Title"] = "ApplyComments";
}

<div>
    <!-- border -->
    <div class="mb-6">
        <h4 class="mb-1">Leaving feedback</h4>
    </div>
    <form asp-action="PassengerFeedback" asp-route-travelId="@Model.TravelId" method="post">
        <!-- row -->
        <div class="mb-3 row">
            <label asp-for="TargetId" class="col-sm-4 col-form-label form-label">Location</label>
            <div class="col-md-8 col-12">
                <select asp-for="TargetId" asp-items="Model.Targets" class="form-select" id="User">
                    @*<option value="@this.Model.AddressId"></option>*@
                </select>
            </div>
        </div>
        <!-- row -->
        <div class="mb-3 row">
            <label asp-for="Rating" class="col-sm-4 col-form-label form-label">Rating</label>
            <div class="col-sm-4 mb-3 mb-lg-0">
                <select asp-for="Rating" class="form-select" value="@this.Model.Rating" id="Rating" required>
                    @for (int i = 0; i <= 5; i++)
                    {
                        <option value="@i">@i</option>
                    }
                </select>
                <span asp-validation-for="Rating" class="alert-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="input-group">
                <span class="col-sm-4 col-form-label form-label">Comment (Optional)</span>
                <div class="col-sm-4 mb-3 mb-lg-0">
                    <textarea class="form-control" aria-label="Comment" type="text" asp-for="Comment" value="@this.Model.Comment" id="Comment"></textarea>
                    <span asp-validation-for="Comment" class="alert-danger"></span>
                </div>
            </div>
        </div>
        <!-- button -->
        <div class="offset-md-4 col-md-8 col-12 mt-3">
            <button type="submit" class="btn btn-primary"> Submit </button>
        </div>
    </form>
</div>

TangraTravel/TangraTravel.MVC/Views/Feedback/Selected.cshtml
@model TangraTravel.MVC.Models.FeedbackDto.FeedbackSelectedByPageViewModel
@{
    ViewData["Title"] = "Selected Feedbacks";
}
<div class="container-fluid px-6 py-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <!-- Page header -->
            <div>
                <div class="border-bottom pb-4 mb-4 ">
                    <div class="mb-2 mb-lg-0">
                        <h3 class="mb-0 fw-bold">Feedbacks</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (Model.FeedbackComments.Count != 0)
    {
        <div class="py-1">
            <div class="col-xl-12 col-lg-12 col-md-12 col-12 mb-12">
                @foreach (var item in Model.FeedbackComments)
                {
                    <div class="row">
                        <div class="card margin-bot-2rem">
                            <div class="card-body">
                                <h4 class="card-title">Rating: @item.Rating</h4>
                                <h5 class="card-title">Author: @item.Author, Username: @item.AuthorUsername</h5>
                                <h5 class="card-title">Recepient: @item.Recepient, Username: @item.RecepientUsername</h5>
                                <p class="card-text">Comment: @item.Comment</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @if (Model.Page > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="Selected"
                           asp-route-page="@(Model.Page - 1)"
                           asp-route-userId="@Model.SelectedUserId" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                }
                <li class="page-item"><a class="page-link" href="#">@Model.Page</a></li>
                @if (Model.Page + 1 <= Model.MaxPage)
                {
                    <li class="page-item">
                        <a class="page-link"
                           asp-action="Selected"
                           asp-route-page="@(Model.Page + 1)"
                           asp-route-userId="@Model.SelectedUserId" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    }
    else
    {
        <h1> History is empty </h1>
    }
</div>

TangraTravel/TangraTravel.MVC/Views/Feedback/ThowardsMe.cshtml
@model TangraTravel.MVC.Models.FeedbackDto.FeedbackByPageViewModel
@{
    ViewData["Title"] = "Received Feedbacks";
    ViewData["Action"] = "ThowardsMe";
}

<partial name="_PersonalFeedbacks" />

TangraTravel/TangraTravel.MVC/Views/Feedback/_PersonalFeedbacks.cshtml
@model TangraTravel.MVC.Models.FeedbackDto.FeedbackByPageViewModel

<div class="container-fluid px-6 py-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <!-- Page header -->
            <div>
                <div class="border-bottom pb-4 mb-4 ">
                    <div class="mb-2 mb-lg-0">
                        <h3 class="mb-0 fw-bold">Feedbacks</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (Model.FeedbackComments.Count != 0)
    {
        <div class="py-1">
            <div class="col-xl-12 col-lg-12 col-md-12 col-12 mb-12">
                @foreach (var item in Model.FeedbackComments)
                {
                    <div class="row">
                        <div class="card margin-bot-2rem" style="margin-bottom: 20px">
                            <div class="card-body">
                                <h4 class="card-title">Rating: @item.Rating</h4>
                                <h5 class="card-title">Author: @item.Author, Username: @item.AuthorUsername</h5>
                                <h5 class="card-title">Recepient: @item.Recepient, Username: @item.RecepientUsername</h5>
                                <p class="card-text">Comment: @item.Comment</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @if (Model.Page > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="@ViewData["Action"]"
                           asp-route-page="@(Model.Page - 1)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                }
                <li class="page-item"><a class="page-link" href="#">@Model.Page</a></li>
                @if (Model.Page + 1 <= Model.MaxPage)
                {
                    <li class="page-item">
                        <a class="page-link"
                           asp-action="@ViewData["Action"]"
                           asp-route-page="@(Model.Page + 1)" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    }
    else
    {
        <h1> History is empty </h1>
    }
</div>