TangraTravel/TangraTravel.MVC/Controllers/CarController.cs
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

using TangraTravel.MVC.Mapper;
using TangraTravel.MVC.Models;
using TangraTravel.MVC.Models.CarDto;
using TangraTravel.Service.Contracts;
using TangraTravel.Service.Models.CarDtos;
using TangraTravel.Service.Exeception.Car;
using TangraTravel.MVC.Controllers.Abstract;

namespace TangraTravel.MVC.Controllers
{
    public class CarController : BaseController
    {
        private readonly ICarService carService;
        private readonly ICustomerService customerService;

        public CarController(ICarService carService, ICustomerService customerService)
        {
            this.carService = carService;
            this.customerService = customerService;
        }

        [Authorize(Roles = "Driver")]
        public async Task<IActionResult> Index()
        {
            int driverId = this.GetUserId();
            var car = await this.carService.GetByUerIdAsync(driverId);

            return View(car);
        }

        [Authorize(Roles = "Driver")]
        public async Task<IActionResult> Update()
        {
            int userId = this.GetUserId();
            var car = await this.carService.GetByUerIdAsync(userId);
            var view = car.ToCarViewModel();
            return this.View(view);
        }

        [HttpPost]
        [Authorize(Roles = "Driver")]
        public async Task<IActionResult> Update(CarViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                this.ModelState.AddModelError(nameof(input.RegistrationNumber), "Registration number is incorrect!");
                return this.View(input);
            }

            int userId = this.GetUserId();
            try
            {
                await this.carService.UpdateAsync(userId, new CarUpdateDto { RegistrationNumber = input.RegistrationNumber });
                return this.View(input);
            }
            catch (CarException ce)
            {
                this.ModelState.AddModelError(nameof(input.RegistrationNumber), ce.Message);
                return this.View(input);
            }
        }

        [Authorize(Roles = "Driver")]
        public async Task<IActionResult> Delete()
        {
            int userId = this.GetUserId();
            try
            {
                await this.carService.DeleteAsync(userId);

                await this.PrepareToken(userId);
                return this.RedirectToAction("Index", "Customer");
            }
            catch (CarException ce)
            {
                var error = new ErrorViewModel() { ErrorMessage = ce.Message };
                return this.View("ErrorRemoveCar", error);
            }
        }

        [Authorize(Roles = "Passenger")]
        public async Task<IActionResult> Register()
        {
            var view = new CarRegisterViewModel();
            view.BasicCarInfromation = await this.carService.TakeBrandsAndModelsAsync(); 

            return this.View(view);
        }

        [HttpPost]
        [Authorize(Roles = "Passenger")]
        public async Task<IActionResult> Register(CarRegisterViewModel input)
        {
            if (!this.ModelState.IsValid || input.ModelId == 0)
            {
                input.BasicCarInfromation = await this.carService.TakeBrandsAndModelsAsync();
                return this.View(input);
            }

            int customerId = this.GetUserId();
            try
            {
                var parameters = new CarCreateDto()
                {
                    ModelId = input.ModelId,
                    Seats = input.Seats,
                    RegistrationNumber = input.RegistrationNumber
                };
                var car = await this.carService.CreateAsync(customerId, parameters);

                await this.PrepareToken(customerId);
                return this.RedirectToAction("Index", "Customer", new { showCar = true });
            }
            catch (CarException ce)
            {
                this.ModelState.AddModelError(nameof(CarRegisterViewModel.RegistrationNumber), ce.Message);
                input.BasicCarInfromation = await this.carService.TakeBrandsAndModelsAsync();

                return this.View(input);
            }
        }

        private async Task PrepareToken(int userId)
        {
            var customer = await this.customerService.GetCustomerAsync(userId);
            await this.UpdateTokenAsync(customer.Avatar.ImageDataURL, customer.Avatar.Alt, customer.SystemStatus);
        }
    }
}

TangraTravel/TangraTravel.MVC/Controllers/CustomerController.cs
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

using TangraTravel.MVC.Mapper;
using TangraTravel.Service.Contracts;
using TangraTravel.MVC.Models.CustomerDto;
using TangraTravel.Service.Exeception.User;
using TangraTravel.MVC.Controllers.Abstract;

namespace TangraTravel.MVC.Controllers
{
    public class CustomerController : BaseController
    {
        private readonly ICustomerService customerService;
        private readonly IAddressService addressService;

        public CustomerController(ICustomerService customerService, IAddressService addressService)
        {
            this.customerService = customerService;
            this.addressService = addressService;
        }

        [HttpGet]
        [Authorize(Roles = "Driver, Passenger")]
        public IActionResult Index(bool showCar)
        {
            var view = this.PrepareViewModel();
            view.Car = showCar;
            return View(view);
        }        

        [HttpGet]
        [Authorize(Roles = "Driver, Passenger")]
        public async Task<IActionResult> Update()
        {
            int userId = this.GetUserId();
            var view = await this.CustomerForUpdateAsync(userId);

            return this.View(view);
        }

        [HttpPost]
        [Authorize(Roles = "Driver, Passenger")]
        public async Task<IActionResult> Update(CustomerUpdateViewModel parameters)
        {
            int userId = this.GetUserId();
            if (!this.ModelState.IsValid)
            {
                var view = await this.CustomerForUpdateAsync(userId);
                return this.View(view);
            }

            var input = parameters.ToCustomerUpdateDto();
            try
            {
                var customer = await this.customerService.UpdateAsync(userId, input);
                var view = customer.ToCustomerUpdateViewModel();
                view.AddressInformation = await this.addressService.PrepareAddressInformationAsync();
                await this.UpdateTokenAsync(view.AvatarUrl, view.Alt);

                return this.RedirectToAction("Update", "Customer");
            }
            catch (InputExistException iee)
            {
                string message = iee.Message;
                if (message.Contains("Email"))
                {
                    this.ModelState.AddModelError(nameof(CustomerUpdateViewModel.Email), message);
                }
                else if (message.Contains("Phone"))
                {
                    this.ModelState.AddModelError(nameof(CustomerUpdateViewModel.PhoneNumber), message);
                }
                else if (message.Contains("Username"))
                {
                    this.ModelState.AddModelError(nameof(CustomerUpdateViewModel.Username), message);
                }

                var view = await this.CustomerForUpdateAsync(userId);
                return this.View(view);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Driver, Passenger")]
        public async Task<IActionResult> ChangePassword(CustomerUpdateViewModel parameters)
        {
            int userId = this.GetUserId();
            if (parameters.Password != parameters.ConfirmPassword)
            {
                this.ModelState.AddModelError(nameof(CustomerUpdateViewModel.Password), "The passwords are not the same!");
                this.ModelState.AddModelError(nameof(CustomerUpdateViewModel.ConfirmPassword), "The passwords are not the same!");
                var view = await this.CustomerForUpdateAsync(userId);
                return this.View("Update", view);
            }

            var input = parameters.ToCustomerUpdateDto();
            var customer = await this.customerService.UpdateAsync(userId, input);
            var viewCustomer = customer.ToCustomerUpdateViewModel();
            viewCustomer.AddressInformation = await this.addressService.PrepareAddressInformationAsync();
            return this.View("Update", viewCustomer);
        }

        private CustomerIndexViewModel PrepareViewModel()
        {
            var view = new CustomerIndexViewModel();
            view.UserId = this.GetUserId();
            view.Email = this.GetUserEmail();
            view.FullName = this.GetUserFullName();
            string[] avatar = this.GetAvatarInformation();
            view.AvatarUrl = avatar[0];
            view.AvatarAlt = avatar[1];

            return view;
        }

        private async Task<CustomerUpdateViewModel> CustomerForUpdateAsync(int userId)
        {
            var customer = await this.customerService.GetCustomerAsync(userId);
            var view = customer.ToCustomerUpdateViewModel();
            view.AddressInformation = await this.addressService.PrepareAddressInformationAsync();

            return view;
        }
    }
}

TangraTravel/TangraTravel.MVC/Views/Customer/Index.cshtml
@model TangraTravel.MVC.Models.CustomerDto.CustomerIndexViewModel
@{
    ViewData["Title"] = "Overview";
}

<div class="container-fluid px-6 py-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <!-- Page header -->
            <div>
                <div class="border-bottom pb-4 mb-4 ">
                    <div class="mb-2 mb-lg-0">
                        <h3 class="mb-0 fw-bold">Overview</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-xl-12 col-lg-12 col-md-12 col-12">
            <!-- Bg -->
            <div class="pt-20 rounded-top" style="background:
                url(../images/background/profile-cover.jpg) no-repeat;
                background-size: cover;">
            </div>
            <div class="bg-white rounded-bottom smooth-shadow-sm ">
                <div class="d-flex align-items-center justify-content-between
                  pt-4 pb-6 px-4">
                    <div class="d-flex align-items-center">
                        <!-- avatar -->
                        <div class="avatar-xxl avatar-indicators avatar-online me-2
                      position-relative d-flex justify-content-end
                      align-items-end mt-n10">
                            <img src="@this.Model.AvatarUrl" class="avatar-xxl
                        rounded-circle border border-4 border-white-color-40" alt="@this.Model.AvatarAlt">
                        </div>
                        <!-- text -->
                        <div class="lh-1">
                            <h2 class="mb-0">
                                @this.Model.FullName
                                <a href="#!" class="text-decoration-none" data-bs-toggle="tooltip" data-placement="top" title="" data-original-title="Beginner">

                                </a>
                            </h2>
                            <p class="mb-0 d-block">@this.Model.Email</p>
                        </div>
                    </div>
                    <div>
                        <a asp-controller="Customer" asp-action="Update" class="btn btn-outline-primary
                      d-none d-md-block">Edit Profile</a>
                    </div>
                </div>
                <!-- nav -->
                <ul class="nav nav-lt-tab px-4" id="pills-tab" role="tablist">
                    @if (Model.Car)
                    {
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="Customer" asp-action="Index">Overview</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link active" href="#">Overview</a>
                        </li>
                    }
                    @if (User.IsInRole("Passenger"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Car" asp-action="Register">Register Car</a>
                        </li>
                    }
                    else if (User.IsInRole("Driver"))
                    {
                        if (Model.Car)
                        {
                            <li class="nav-item">
                                <a class="nav-link active" href="#">Car</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Customer" asp-action="Index" asp-route-showCar="true">Car</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>

    @if (@Model.Car)
    {
        <!--Cards-->
        <div class="py-6">
            <div class="row">
                <div class="col-xl-6 col-lg-12 col-md-12 col-12 mb-6">
                    <div class="card">
                        <!-- card body -->
                        <div class="card-body">
                            @(await Component.InvokeAsync("ShowCar",Model.UserId))
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <!--Cards-->
        <div class="py-6">
            <!-- row -->
            <div class="row">
                <div class="col-xl-6 col-lg-12 col-md-12 col-12 mb-6">
                    <!-- card -->
                    <div class="card">
                        <!-- card body -->
                        <div class="card-body">
                            <!-- card title -->
                            <h4 class="card-title mb-4">Soon Travels</h4>
                            @(await Component.InvokeAsync("NearestTravels",Model.UserId))
                        </div>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-12 col-md-12 col-12 mb-6">
                    <!-- card -->
                    <div class="card">
                        <!-- card body -->
                        @(await Component.InvokeAsync("FeedbackProfile", Model.UserId))
                    </div>
                </div>
            </div>
        </div>
    }
</div>

TangraTravel/TangraTravel.MVC/Views/Customer/Update.cshtml
@using TangraTravel.Data.Enum
@model TangraTravel.MVC.Models.CustomerDto.CustomerUpdateViewModel
@{
    ViewData["Title"] = "Update Profile";
}

<div class="container-fluid px-6 py-4">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <!-- Page header -->
            <div>
                <div class="border-bottom pb-4 mb-4 ">
                    <div class="mb-2 mb-lg-0">
                        <h3 class="mb-0 fw-bold">General</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- card -->
    <div class="card">
        <!-- card body -->
        <div class="card-body">
            <div class=" mb-6">
                <h4 class="mb-1">General Settings</h4>
            </div>
            <div class="row align-items-center mb-8">
                <div class="col-md-3 mb-3 mb-md-0">
                    <h5 class="mb-0">Avatar</h5>
                </div>
                <div class="col-md-9">
                    <div class="d-flex align-items-center">
                        <div class="me-3">
                            <img src="@this.Model.AvatarUrl" class="rounded-circle avatar avatar-lg" alt="@this.Model.Alt">
                        </div>
                    </div>
                </div>
            </div>
            <!-- col -->
            <div class="row mb-8">
                <div class="col-md-3 mb-3 mb-md-0">
                    <!-- heading -->
                    <h5 class="mb-0">Cover photo</h5>
                </div>
                <div class="col-md-9">
                    <!-- dropzone input -->
                    <div>
                        <form asp-controller="Customer" asp-action="Update" method="post" class="mb-3 " enctype="multipart/form-data">
                            <div class="fallback">
                                <input name="file" type="file" multiple="multiple" />
                            </div>
                            <div>
                                <button type="submit" class="btn btn-outline-white">Change</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div>
                <!-- border -->
                <div class="mb-6">
                    <h4 class="mb-1">Basic information</h4>
                </div>
                <form asp-action="Update" method="post">
                    <!-- row -->
                    <div class="mb-3 row">
                        <label for="" class="col-sm-4 col-form-label
                          form-label">Full name</label>
                        <div class="col-sm-4 mb-3 mb-lg-0">
                            <input type="text" asp-for="FirstName" class="form-control" id="fullName" required>
                            <span asp-validation-for="FirstName" class="alert-danger"></span>
                        </div>
                        <div class="col-sm-4">
                            <input type="text" asp-for="LastName" class="form-control" value="@this.Model.LastName" id="lastName" required>
                            <span asp-validation-for="LastName" class="alert-danger"></span>
                        </div>
                    </div>
                    <!-- row -->
                    <div class="mb-3 row">
                        <label asp-for="Email" class="col-sm-4 col-form-label
                          form-label">Email</label>
                        <div class="col-md-8 col-12">
                            <input type="email" asp-for="Email" class="form-control" value="@this.Model.Email" id="email" required>
                            <span asp-validation-for="Email" class="alert-danger"></span>
                        </div>
                    </div>
                    <!-- row -->
                    <div class="mb-3 row">
                        <label asp-for="Username" class="col-sm-4 col-form-label
                          form-label">Username</label>
                        <div class="col-md-8 col-12">
                            <input type="text" asp-for="Username" class="form-control" placeholder="@this.Model.Username" id="phone" required>
                            <span asp-validation-for="Username" class="alert-danger"></span>
                        </div>
                    </div>
                    <!-- row -->
                    <div class="mb-3 row">
                        <label asp-for="PhoneNumber" class="col-sm-4 col-form-label
                          form-label">Phone</label>
                        <div class="col-md-8 col-12">
                            <input type="text" asp-for="PhoneNumber" class="form-control" placeholder="@this.Model.PhoneNumber" id="phone" required>
                            <span asp-validation-for="PhoneNumber" class="alert-danger"></span>
                        </div>
                    </div>
                    <!-- row -->
                    <div class="mb-3 row">
                        <label asp-for="@this.Model.AddressId" class="col-sm-4 col-form-label form-label">Location</label>
                        <div class="col-md-8 col-12">
                            <select asp-for="AddressId" asp-items="Model.AddressInformation" class="form-select" id="location">
                                <option value="@this.Model.AddressId"></option>
                            </select>
                        </div>
                    </div>
                    <!-- button -->
                    <div class="offset-md-4 col-md-8 col-12 mt-3">
                        <button type="submit" class="btn btn-primary"> Save Changes </button>
                    </div>
                </form>
                <!-- Change Password-->
                <div class="mb-6 mt-6">
                    <h4 class="mb-1">Change your password</h4>
                </div>
                <form asp-action="ChangePassword" method="post">
                    <!-- row -->
                    <div class="mb-3 row">
                        <label asp-for="Password" class="col-sm-4 col-form-label form-label">New Password</label>
                        <div class="col-md-8 col-12">
                            <input type="password" asp-for="Password" class="form-control" placeholder="Enter Current password" id="currentPassword" required>
                            <span asp-validation-for="Password" class="alert-danger"></span>
                        </div>
                    </div>
                    <!-- row -->
                    <div class="mb-3 row">
                        <label asp-for="ConfirmPassword" class="col-sm-4 col-form-label form-label">Confirm New Password</label>
                        <div class="col-md-8 col-12">
                            <input type="password" asp-for="ConfirmPassword" class="form-control" placeholder="Enter New password" id="currentNewPassword" required>
                            <span asp-validation-for="ConfirmPassword" class="alert-danger"></span>
                        </div>
                    </div>
                    <!-- row -->
                    <div class="row align-items-center">
                        <!-- list -->
                        <div class="offset-md-4 col-md-8 col-12 mt-4">
                            <h6 class="mb-1">Password requirements:</h6>
                            <p>Ensure that these requirements are met:</p>
                            <ul>
                                <li> Minimum 8 characters long the more, the better</li>
                                <li>At least one lowercase character</li>
                                <li>At least one uppercase character</li>
                                <li> At least one number, symbol, or whitespace character </li>
                            </ul>
                            <button type="submit" class="btn btn-primary"> Save Changes </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}